# This workflow will build PRs submitted to the main branch.

name: PR Builder

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
  workflow_dispatch:

# Avoid running multiple builds for the same PR.
concurrency:
  group: pr-builder-${{ github.ref }}
  cancel-in-progress: true

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        pnpm-version: [10.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Project
        uses: ./.github/actions/build
        with:
          node-version: ${{ matrix.node-version }}
          pnpm-version: ${{ matrix.pnpm-version }}
