# This workflow will build PRs submitted to the main branch.

name: PR Builder

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
  workflow_dispatch:

# Avoid running multiple builds for the same PR.
concurrency:
  group: pr-builder-${{ github.ref }}
  cancel-in-progress: true

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [lts/*]
        pnpm-version: [latest]
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        id: setup-pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ matrix.pnpm-version }}
          run_install: false

      - name: Setup node
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install Dependencies
        id: install-dependencies
        run: |
          tree -L 1
          ls -l pnpm-lock.yaml
          pnpm store prune
          pnpm install

      - name: Build Project
        id: build
        run:  pnpm build

      - name: Build Storybook
        id: build-storybook
        run: pnpm build-storybook
