# This workflow will publish a package to the npm registry on release.
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish

on:
  release:
    types: [created]

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  publish-npm:
    name: Publish NPM
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [lts/*]
        pnpm-version: [latest]
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        id: setup-pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ matrix.pnpm-version }}
          run_install: false

      - name: Setup node
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install Dependencies
        id: install-dependencies
        run: pnpm install

      - name: Build
        id: build
        run:  pnpm build

      - name: Publish
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{env.NPM_TOKEN}}

      