# This workflow will publish a package to the npm registry on release.
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Release

on:
  push:
    branches:
      - main

env:
  CI: true

concurrency: ${{ github.workflow }}-${{ github.ref }}
permissions:
      contents: write
      pull-requests: write
jobs:
  release:
    strategy:
      matrix:
        node-version: [20.x]
        pnpm-version: [10.x]
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4

      - name: Build Project
        uses: ./.github/actions/build
        with:
          node-version: ${{ matrix.node-version }}
          pnpm-version: ${{ matrix.pnpm-version }}
      
      - name: next version
        id: next
        run: |
          pnpm changeset status --output=release.json
          echo "NEXT_VERSION=$(jq -r '.releases[0].newVersion' release.json)" >> "$GITHUB_ENV"

      - name: Create and publish versions
        uses: changesets/action@v1
        with:
          commit: "chore(release): ${{ env.NEXT_VERSION }}"
          title:  "chore(release): ${{ env.NEXT_VERSION }}"
          publish: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
